const musicGenres = {
  Alternative: [
    "Alternative Rock",
    "College Rock",
    "Experimental Rock",
    "Goth Rock",
    "Grunge",
    "Hardcore Punk",
    "Hard Rock",
    "Indie Rock",
    "New Wave",
    "Progressive Rock",
    "Punk",
    "Shoegaze",
    "Steampunk",
  ],
  Blues: [
    "Acoustic Blues",
    "Chicago Blues",
    "Classic Blues",
    "Contemporary Blues",
    "Country Blues",
    "Delta Blues",
    "Electric Blues",
  ],
  Country: [
    "Alternative Country",
    "Americana",
    "Bluegrass",
    "Contemporary Bluegrass",
    "Contemporary Country",
    "Country Gospel",
    "Honky Tonk",
    "Outlaw Country",
    "Traditional Bluegrass",
    "Traditional Country",
    "Urban Cowboy",
  ],
  Electronic: [
    "Ambient",
    "Crunk",
    "Downtempo",
    "Electro",
    "Electronica",
    "Electronic Rock",
    "Industrial",
    "Breakbeat",
    "Dubstep",
    "Exercise",
    "Garage",
    "Hardcore",
    "Hard Dance",
    "Hi-NRG / Eurodance",
    "House",
    "Jackin House",
    "Jungle/Drum’n'bass",
    "Techno",
    "Trance",
    "Acid Breaks",
    "Chill Out",
    "Drumstep",
    "Jazzstep",
    "Liquid Funk",
    "Glitchstep",
    "Post Dubstep",
    "Dubtronica",
    "Alternative Dance",
    "Coldwave",
    "Darkwave",
    "Synthpop",
    "Breakcore",
    "Synthwave",
    "Trancecore",
    "Hard House",
    "Acid House",
    "Progressive House",
    "Aggrotech",
    "Dark Electro",
    "Acid Techno",
    "Progressive Trance",
    "Psychedelic Trance ",
  ],
  Hip_Hop_Rap: [
    "Alternative Rap",
    "Bounce",
    "Dirty South",
    "East Coast Rap",
    "Gangsta Rap",
    "Hardcore Rap",
    "Hip-Hop",
    "Latin Rap",
    "Old School Rap",
    "Rap",
    "Underground Rap",
    "West Coast Rap",
    "Alternative Hip-Hop",
    "Battle Rap",
    "Crunk",
    "Southern Rap",
    "Trap",
    "Country Rap",
    "Rap Rock",
    "G-funk",
  ],
  Jazz: [
    "Acid Jazz",
    "Avant-Garde Jazz",
    "Big Band",
    "Blue Note",
    "Contemporary Jazz",
    "Cool",
    "Crossover Jazz",
    "Dixieland",
    "Ethio-jazz",
    "Fusion",
    "Hard Bop",
    "Latin Jazz",
    "Mainstream Jazz",
    "Ragtime",
    "Smooth Jazz",
    "Trad Jazz",
    "Swing Jazz",
  ],
  Latino: [
    "Alternativo & Rock Latino",
    "Baladas y Boleros",
    "Brazilian",
    "Contemporary Latin",
    "Latin Jazz",
    "Pop Latino",
    "Raíces",
    "Reggaeton y Hip-Hop",
    "Regional Mexicano",
    "Salsa y Tropical",
  ],
  Metal: [
    "Heavy Metal",
    "Thrash Metal",
    "Death Metal",
    "Black Metal",
    "Doom Metal",
    "Stoner Metal",
    "Sludge",
    "Blackened Death",
    "Blackened Thrash",
    "Grindcore",
    "Deathgrind",
    "Metalcore",
    "Deathcore",
    "Melodic Death Metal",
    "Progressive Metal",
    "Progressive Death Metal",
    "Funeral Doom",
    "Groove Metal",
    "Folk Metal",
    "Industrial Metal",
    "Funk Metal",
    "Hair Metal",
    "Sothern Metal",
    "Goregrind",
    "Nu Metal",
    "Power Metal",
    "New Wave of British Heavy Metal",
    "New Wave of American Heavy Metal",
    "Post Black Metal",
    "Post Metal",
    "Crossover Thrash",
    "Gothic Metal",
    "Alternative Metal",
    "Symphonic Metal",
    "Symphonic Black Metal",
    "Symphonic Death Metal",
    "Death 'n' Roll",
    "Technical Death Metal",
    "Death Doom",
    "Speed Metal",
    "Mathcore",
    "Djent",
  ],
  Pop: ["Adult Contemporary", "Britpop", "Pop Rock", "Soft Rock", "Teen Pop"],
  Punk: [
    "Afro Punk",
    "Anarcho Punk",
    "Art Punk",
    "Christian Punk",
    "Crust Punk",
    "Deathrock",
    "Garage Punk",
    "Glam Punk",
    "Hardcore Punk",
    "Horror Punk",
    "Oi!",
    "Queercore",
    "Riot Grrrl",
    "Skate Punk",
    "Street Punk",
    "Celtic Punk",
    "Folk Punk",
    "Pop Punk",
    "Ska Punk",
    "D-beat",
    "Emo",
    "Post Hardcore",
    "Powerviolence",
    "Screamo",
    "Thrashcore",
  ],
  R_B_Soul: [
    "Contemporary R&B",
    "Disco",
    "Doo Wop",
    "Funk",
    "Motown",
    "Neo-Soul",
    "Quiet Storm",
    "Soul",
  ],
  Reggae: ["Dancehall", "Dub", "Roots Reggae", "Ska"],
  Rock: [
    "Arena Rock",
    "Blues-Rock",
    "British Invasion",
    "Glam Rock",
    "Hard Rock",
    "Prog-Rock/Art Rock",
    "Psychedelic Rock",
    "Rock & Roll",
    "Rockabilly",
    "Roots Rock",
    "Southern Rock",
    "Surf Rock",
    "Post Grunge",
    "Classic Rock",
    "Garage Rock",
    "Math Rock",
    "Post Rock",
    "Soft Rock",
  ],
};

// Returns all genres - object holding genres
function getAllGenres() {
  return musicGenres;
}

// Returns random genre - array holding subgenres
function getRandomGenre() {
  return musicGenres[
    Object.keys(musicGenres)[
      Math.floor(Math.random() * Object.keys(musicGenres).length)
    ]
  ];
}

// Returns random subgenre - string
function getRandomSubgenre() {
  let key =
    musicGenres[
      Object.keys(musicGenres)[
        Math.floor(Math.random() * Object.keys(musicGenres).length)
      ]
    ];
  let length = key.length;
  return key[Math.floor(Math.random() * length)];
}

module.exports = {
  getAllGenres: getAllGenres,
  getRandomGenre: getRandomGenre,
  getRandomSubgenre: getRandomSubgenre,
};

// Genres: 13
// Subgenres: 222
